let Lastname = "Ribochenko";
let name = "Mihail";
alert(name+ Lastname);
let str = "!!!";
alert(str);
let str2, str3, str4, str5, str6;
str2 = "java";
str3 = "script";
alert(str2 + str3);
str4 = "hello ";
str5 = "world";
alert(str4 + str5);
str6 = "Mirius";
alert(str6 .length);